### ISSUE TITLE
Need to specify an explicit version for reproductible builds

### ISSUE THREAD

**Issue by LouisCAD** [msink/kotlin-pi#1]
The fact you use an unknown version makes your "benchmark" not so trustworthy since we don't know which version is used at the time of the benchmark, and there's no way to see the evolution across multiple releases à Kotlin/JVM and Kotlin/Native.
See here: https://github.com/msink/kotlin-pi/blob/48fe5dddff3194430f53c355ed2c626d3599275c/build.gradle#L25

**Comment by msink** [comment]
Fixed, please reopen if I misunderstood

**Comment by LouisCAD** [comment]
That's perfect now!
